package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Antecedente generated by hbm2java
 */
public class Antecedente implements java.io.Serializable {

    private int antecedenteid;
    private Historialclinico historialclinico;
    private Date fecha;
    private String antecedente;
    private String tipo;

    public Antecedente() {
    }

    public Antecedente(int antecedenteid, Historialclinico historialclinico, Date fecha, String antecedente, String tipo) {
        this.antecedenteid = antecedenteid;
        this.historialclinico = historialclinico;
        this.fecha = fecha;
        this.antecedente = antecedente;
        this.tipo = tipo;
    }

    public int getAntecedenteid() {
        return this.antecedenteid;
    }

    public void setAntecedenteid(int antecedenteid) {
        this.antecedenteid = antecedenteid;
    }

    public Historialclinico getHistorialclinico() {
        return this.historialclinico;
    }

    public void setHistorialclinico(Historialclinico historialclinico) {
        this.historialclinico = historialclinico;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getAntecedente() {
        return this.antecedente;
    }

    public void setAntecedente(String antecedente) {
        this.antecedente = antecedente;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Override
    public String toString() {
        return antecedente;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Antecedente)) {
            return false;
        }
        Antecedente antecedente = (Antecedente) o;
        return (this.antecedenteid == antecedente.antecedenteid);

    }
}
