package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

/**
 * Archivo generated by hbm2java
 */
public class Archivo implements java.io.Serializable {

    private int archivoid;
    private Odontograma odontograma;
    private Historialclinico historialclinico;
    private String tipo;
    private byte[] bytes;

    public Archivo() {
    }

    public Archivo(int archivoid, Odontograma odontograma, Historialclinico historialclinico, String tipo, byte[] bytes) {
        this.archivoid = archivoid;
        this.odontograma = odontograma;
        this.historialclinico = historialclinico;
        this.tipo = tipo;
        this.bytes = bytes;
    }

    public int getArchivoid() {
        return this.archivoid;
    }

    public void setArchivoid(int archivoid) {
        this.archivoid = archivoid;
    }

    public Odontograma getOdontograma() {
        return this.odontograma;
    }

    public void setOdontograma(Odontograma odontograma) {
        this.odontograma = odontograma;
    }

    public Historialclinico getHistorialclinico() {
        return this.historialclinico;
    }

    public void setHistorialclinico(Historialclinico historialclinico) {
        this.historialclinico = historialclinico;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public byte[] getBytes() {
        return this.bytes;
    }

    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }

    @Override
    public String toString() {
        return archivoid + " " + odontograma.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Archivo)) {
            return false;
        }
        Archivo archivo = (Archivo) o;
        return (this.archivoid == archivo.archivoid);

    }
}
