package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import Util.HibernateUtil;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Hibernate;

/**
 * Cabecerafactura generated by hbm2java
 */
public class Cabecerafactura implements java.io.Serializable {

    private int cabecerafactura;
    private Paciente paciente;
    private BigDecimal numerofactura;
    private String total;
    private String observaciones;
    private String descuento;
    private String otroimpuestos;
    private String iva;
    private Set detalles = new HashSet(0);

    public Cabecerafactura() {
    }

    public Cabecerafactura(int cabecerafactura, Paciente paciente, BigDecimal numerofactura, String total, String observaciones, String descuento, String otroimpuestos, String iva) {
        this.cabecerafactura = cabecerafactura;
        this.paciente = paciente;
        this.numerofactura = numerofactura;
        this.total = total;
        this.observaciones = observaciones;
        this.descuento = descuento;
        this.otroimpuestos = otroimpuestos;
        this.iva = iva;
    }

    public Cabecerafactura(int cabecerafactura, Paciente paciente, BigDecimal numerofactura, String total, String observaciones, String descuento, String otroimpuestos, String iva, Set detalles) {
        this.cabecerafactura = cabecerafactura;
        this.paciente = paciente;
        this.numerofactura = numerofactura;
        this.total = total;
        this.observaciones = observaciones;
        this.descuento = descuento;
        this.otroimpuestos = otroimpuestos;
        this.iva = iva;
        this.detalles = detalles;
    }

    public int getCabecerafactura() {
        return this.cabecerafactura;
    }

    public void setCabecerafactura(int cabecerafactura) {
        this.cabecerafactura = cabecerafactura;
    }

    public Paciente getPaciente() {
        Hibernate.initialize(this.paciente);
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public BigDecimal getNumerofactura() {
        return this.numerofactura;
    }

    public void setNumerofactura(BigDecimal numerofactura) {
        this.numerofactura = numerofactura;
    }

    public String getTotal() {
        return this.total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getDescuento() {
        return this.descuento;
    }

    public void setDescuento(String descuento) {
        this.descuento = descuento;
    }

    public String getOtroimpuestos() {
        return this.otroimpuestos;
    }

    public void setOtroimpuestos(String otroimpuestos) {
        this.otroimpuestos = otroimpuestos;
    }

    public String getIva() {
        return this.iva;
    }

    public void setIva(String iva) {
        this.iva = iva;
    }

    public Set getDetalles() {
        return this.detalles;
    }

    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }

    @Override
    public String toString() {
        return cabecerafactura + " " + otroimpuestos;
    }
//    @Override
//    public boolean equals(Object o) {
//        if (!(o instanceof Cabecerafactura)) {
//            return false;
//        }
//        Cabecerafactura cabecerafactura = (Cabecerafactura) o;
//        return (this.cabecerafactura == cabecerafactura.cabecerafactura);
//
//    }
}
