package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.hibernate.Hibernate;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

    private int categoriaid;
    private String descripcion;
    private Set medicos = new HashSet(0);

    public Categoria() {
    }

    public Categoria(int categoriaid, String descripcion) {
        this.categoriaid = categoriaid;
        this.descripcion = descripcion;
    }

    public Categoria(int categoriaid, String descripcion, Set medicos) {
        this.categoriaid = categoriaid;
        this.descripcion = descripcion;
        this.medicos = medicos;
    }

    public int getCategoriaid() {
        return this.categoriaid;
    }

    public void setCategoriaid(int categoriaid) {
        this.categoriaid = categoriaid;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getMedicos() {
        return this.medicos;
    }

    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }

    @Override
    public String toString() {
        return descripcion;
    }

    @Override
    public boolean equals(Object o) {
         if (o == null || !(o instanceof Categoria)) {
            return false;
        }
        if (o == this) {
            return true;
        }

        return categoriaid == ((Categoria) o).getCategoriaid();


    }
}
