package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Transient;
import org.hibernate.Hibernate;

/**
 * Cita generated by hbm2java
 */
public class Cita implements java.io.Serializable {

    private int citaid;
    private Paciente paciente;
    private Medico medico;
    private BigDecimal numero;
    private String notas;
    private Date duracion;
    private String tipo;
    private String descripcion;
    private String acude;
    private Date fechacita;

    public Cita() {
    }

    public Cita(int citaid, Paciente paciente, Medico medico, BigDecimal numero, String notas, Date duracion, String tipo, String descripcion, Date horario, String acude, Date fechacita) {
        this.citaid = citaid;
        this.paciente = paciente;
        this.medico = medico;
        this.numero = numero;
        this.notas = notas;
        this.duracion = duracion;
        this.tipo = tipo;
        this.descripcion = descripcion;
        this.acude = acude;
        this.fechacita = fechacita;
    }
    @Transient
    private String dateForFilter;
    @Transient
    private Integer position;
    @Transient
    private String horariostring;

    public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getHorarioString() {
        return horariostring;
    }

    public void setHorarioString(String horariostring) {
        this.horariostring = horariostring;
    }

    public int getCitaid() {
        return this.citaid;
    }

    public void setCitaid(int citaid) {
        this.citaid = citaid;
    }

    public Paciente getPaciente() {
        Hibernate.initialize(this.paciente);
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public Medico getMedico() {
        Hibernate.initialize(this.medico);
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

    public BigDecimal getNumero() {
        return this.numero;
    }

    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }

    public String getNotas() {
        return this.notas;
    }

    public void setNotas(String notas) {
        this.notas = notas;
    }

   
    public Date getDuracion() {
        return this.duracion;
    }

    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getAcude() {
        return this.acude;
    }

    public void setAcude(String acude) {
        this.acude = acude;
    }

    public Date getFechacita() {
        return this.fechacita;
    }

    public void setFechacita(Date fechacita) {
        this.fechacita = fechacita;
    }

    @Override
    public String toString() {
        return citaid + " " + paciente.getNombre();
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Cita)) {
            return false;
        }
        Cita cita = (Cita) o;
        return (this.citaid == cita.citaid);

    }
}
