package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Transient;
import org.hibernate.Hibernate;

/**
 * Consulta generated by hbm2java
 */
public class Consulta implements java.io.Serializable {

    private int consultaid;
    private Paciente paciente;
    private Medico medico;
    private Tratamiento tratamiento;
    private Date fechaconsulta;
    private int sist;
    private int diast;
    private int pulsaciones;
    private int ritmorespiratorio;
    private int temperatura;
    private int altura;
    private int peso;
    private int imc;
    private String observacion;
    private String anamnesis;
    private String exploracion;
    private Diagnostico diagnostico;
    
     @Transient
    private String dateForFilter;
    @Transient
    private Integer position;

    public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }


    public Consulta() {
        diagnostico = new Diagnostico();
        tratamiento = new Tratamiento();
    }

    public Consulta(int consultaid, Paciente paciente, Medico medico, Date fechaconsulta, int sist, int diast, int pulsaciones, int ritmorespiratorio, int temperatura, int altura, int peso, int imc) {
        this.consultaid = consultaid;
        this.paciente = paciente;
        this.medico = medico;
        this.fechaconsulta = fechaconsulta;
        this.sist = sist;
        this.diast = diast;
        this.pulsaciones = pulsaciones;
        this.ritmorespiratorio = ritmorespiratorio;
        this.temperatura = temperatura;
        this.altura = altura;
        this.peso = peso;
        this.imc = imc;
    }

    public Consulta(int consultaid, Paciente paciente, Medico medico, Tratamiento tratamiento, Date fechaconsulta, int sist, int diast, int pulsaciones, int ritmorespiratorio, int temperatura, int altura, int peso, int imc, String observacion, String anamnesis, String exploracion, Diagnostico diagnostico) {
        this.consultaid = consultaid;
        this.paciente = paciente;
        this.medico = medico;
        this.tratamiento = tratamiento;
        this.fechaconsulta = fechaconsulta;
        this.sist = sist;
        this.diast = diast;
        this.pulsaciones = pulsaciones;
        this.ritmorespiratorio = ritmorespiratorio;
        this.temperatura = temperatura;
        this.altura = altura;
        this.peso = peso;
        this.imc = imc;
        this.observacion = observacion;
        this.anamnesis = anamnesis;
        this.exploracion = exploracion;
        this.diagnostico = diagnostico;
       
    }

    public int getConsultaid() {
        return this.consultaid;
    }

    public void setConsultaid(int consultaid) {
        this.consultaid = consultaid;
    }

    public Paciente getPaciente() {
        Hibernate.initialize(this.paciente);
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public Medico getMedico() {
        Hibernate.initialize(this.medico);
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

    public Tratamiento getTratamiento() {
        Hibernate.initialize(this.tratamiento);
        return this.tratamiento;
    }

    public void setTratamiento(Tratamiento tratamiento) {
        this.tratamiento = tratamiento;
    }

    public Date getFechaconsulta() {
        return this.fechaconsulta;
    }

    public void setFechaconsulta(Date fechaconsulta) {
        this.fechaconsulta = fechaconsulta;
    }

    public int getSist() {
        return this.sist;
    }

    public void setSist(int sist) {
        this.sist = sist;
    }

    public int getDiast() {
        return this.diast;
    }

    public void setDiast(int diast) {
        this.diast = diast;
    }

    public int getPulsaciones() {
        return this.pulsaciones;
    }

    public void setPulsaciones(int pulsaciones) {
        this.pulsaciones = pulsaciones;
    }

    public int getRitmorespiratorio() {
        return this.ritmorespiratorio;
    }

    public void setRitmorespiratorio(int ritmorespiratorio) {
        this.ritmorespiratorio = ritmorespiratorio;
    }

    public int getTemperatura() {
        return this.temperatura;
    }

    public void setTemperatura(int temperatura) {
        this.temperatura = temperatura;
    }

    public int getAltura() {
        return this.altura;
    }

    public void setAltura(int altura) {
        this.altura = altura;
    }

    public int getPeso() {
        return this.peso;
    }

    public void setPeso(int peso) {
        this.peso = peso;
    }

    public int getImc() {
        return this.imc;
    }

    public void setImc(int imc) {
        this.imc = imc;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public String getAnamnesis() {
        return this.anamnesis;
    }

    public void setAnamnesis(String anamnesis) {
        this.anamnesis = anamnesis;
    }

    public String getExploracion() {
        return this.exploracion;
    }

    public void setExploracion(String exploracion) {
        this.exploracion = exploracion;
    }

    public Diagnostico getDiagnostico() {
        Hibernate.initialize(this.diagnostico);
        return this.diagnostico;
    }

    public void setDiagnostico(Diagnostico diagnostico) {
        this.diagnostico = diagnostico;
    }

    
    @Override
    public String toString() {
        return consultaid + " " + tratamiento;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Consulta)) {
            return false;
        }
        Consulta consulta = (Consulta) o;
        return (this.consultaid == consulta.consultaid);

    }
}
