package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Transient;
import org.hibernate.Hibernate;

/**
 * Informe generated by hbm2java
 */
public class Informe implements java.io.Serializable {

    private int informeid;
    private Paciente paciente;
    private Medico medico;
    private BigDecimal numero;
    private Date fecha;
    private String texto;
    private String tipo;
    
        @Transient
    private String dateForFilter;
    @Transient
    private Integer position;

    public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Informe() {
    }

    public Informe(int informeid, Paciente paciente, Medico medico, BigDecimal numero, Date fecha, String texto, String tipo) {
        this.informeid = informeid;
        this.paciente = paciente;
        this.medico = medico;
        this.numero = numero;
        this.fecha = fecha;
        this.texto = texto;
        this.texto = tipo;
    }

    public int getInformeid() {
        return this.informeid;
    }

    public void setInformeid(int informeid) {
        this.informeid = informeid;
    }

    public Paciente getPaciente() {
        Hibernate.initialize(this.paciente);
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public Medico getMedico() {
        Hibernate.initialize(this.medico);
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

    public BigDecimal getNumero() {
        return this.numero;
    }

    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Override
    public String toString() {
        return informeid + " " + paciente.getNombre();
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Informe)) {
            return false;
        }
        Informe informe = (Informe) o;
        return (this.informeid == informe.informeid);

    }
}
