package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Transient;
import org.hibernate.Hibernate;
import org.hibernate.validator.Email;
import org.hibernate.validator.Pattern;

/**
 * Medico generated by hbm2java
 */
public class Medico implements java.io.Serializable {

    private int medicoid;
    private Categoria categoria;
    private String nombre;
    private String segundonombre;
    private String apellidopaterno;
    private String apellidomaterno;
    private String numerohijos;
    private String cedula;
    private String genero;
    private String edad;
    private String telefono;
    private String celular;
    private String direccion;
    private String email;
    private String estadocivil;
    private String nacionalidad;
    private String profesion;
    private String lugartrabajo;
    private Date fechanacimiento;
    private String provincia;
    private String localidad;
    private Date fechaalta;
    private Date fechabaja;
    private Double sueldo;
    private String contrasena;
    private boolean administrador;
    private boolean activo;
   /* private Set citas = new HashSet(0);
    private Set recetas = new HashSet(0);
    private Set pacientes = new HashSet(0);
    private Set odontogramas = new HashSet(0);
    private Set consultas = new HashSet(0);
    private Set informes = new HashSet(0);*/
    @Transient
    private String dateForFilter;
    @Transient
    private Integer position;

    public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Medico() {
    }

    public Medico(int medicoid, String nombre, String segundonombre, String apellidopaterno, String apellidomaterno, String numerohijos, String cedula, String genero, String edad, String telefono, String celular, String direccion, String email, String estadocivil, String nacionalidad, String profesion, String lugartrabajo, Date fechanacimiento, String provincia, String localidad, Date fechaalta, Date fechabaja, Double sueldo, String contrasena, boolean administrador, boolean activo) {
        this.medicoid = medicoid;
        this.nombre = nombre;
        this.segundonombre = segundonombre;
        this.apellidopaterno = apellidopaterno;
        this.apellidomaterno = apellidomaterno;
        this.numerohijos = numerohijos;
        this.cedula = cedula;
        this.genero = genero;
        this.edad = edad;
        this.telefono = telefono;
        this.celular = celular;
        this.direccion = direccion;
        this.email = email;
        this.estadocivil = estadocivil;
        this.nacionalidad = nacionalidad;
        this.profesion = profesion;
        this.lugartrabajo = lugartrabajo;

        this.fechanacimiento = fechanacimiento;
        this.provincia = provincia;
        this.localidad = localidad;

        this.fechaalta = fechaalta;
        this.fechabaja = fechabaja;
        this.sueldo = sueldo;
        this.contrasena = contrasena;
        this.administrador = administrador;
        this.activo = activo;
    }

    public Medico(int medicoid, Categoria categoria, String nombre, String segundonombre, String apellidopaterno, String apellidomaterno, String numerohijos, String cedula, String genero, String edad, String telefono, String celular, String direccion, String email, String estadocivil, String nacionalidad, String profesion, String lugartrabajo, Date fechanacimiento, String provincia, String localidad, Date fechaalta, Date fechabaja, Double sueldo, String contrasena, boolean administrador, boolean activo, Set citas, Set recetas, Set pacientes, Set odontogramas, Set consultas, Set informes) {
        this.medicoid = medicoid;
        this.categoria = categoria;
        this.nombre = nombre;
        this.segundonombre = segundonombre;
        this.apellidopaterno = apellidopaterno;
        this.apellidomaterno = apellidomaterno;
        this.numerohijos = numerohijos;
        this.cedula = cedula;
        this.genero = genero;
        this.edad = edad;
        this.telefono = telefono;
        this.celular = celular;
        this.direccion = direccion;
        this.email = email;
        this.estadocivil = estadocivil;
        this.nacionalidad = nacionalidad;
        this.profesion = profesion;
        this.lugartrabajo = lugartrabajo;

        this.fechanacimiento = fechanacimiento;
        this.provincia = provincia;
        this.localidad = localidad;

        this.fechaalta = fechaalta;
        this.fechabaja = fechabaja;
        this.sueldo = sueldo;
        this.contrasena = contrasena;
        this.administrador = administrador;
        this.activo = activo;
        /*this.citas = citas;
        this.recetas = recetas;
        this.pacientes = pacientes;
        this.odontogramas = odontogramas;
        this.consultas = consultas;
        this.informes = informes;*/
    }

    public int getMedicoid() {
        return this.medicoid;
    }

    public void setMedicoid(int medicoid) {
        this.medicoid = medicoid;
    }

    public Categoria getCategoria() {
        Hibernate.initialize(this.categoria);
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getSegundonombre() {
        return this.segundonombre;
    }

    public void setSegundonombre(String segundonombre) {
        this.segundonombre = segundonombre;
    }

    public String getApellidopaterno() {
        return this.apellidopaterno;
    }

    public void setApellidopaterno(String apellidopaterno) {
        this.apellidopaterno = apellidopaterno;
    }

    public String getApellidomaterno() {
        return this.apellidomaterno;
    }

    public void setApellidomaterno(String apellidomaterno) {
        this.apellidomaterno = apellidomaterno;
    }

    public String getNumerohijos() {
        return this.numerohijos;
    }

    public void setNumerohijos(String numerohijos) {
        this.numerohijos = numerohijos;
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getGenero() {
        return this.genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getEdad() {
        return this.edad;
    }

    public void setEdad(String edad) {
        this.edad = edad;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEstadocivil() {
        return this.estadocivil;
    }

    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }

    public String getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public String getProfesion() {
        return this.profesion;
    }

    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

    public String getLugartrabajo() {
        return this.lugartrabajo;
    }

    public void setLugartrabajo(String lugartrabajo) {
        this.lugartrabajo = lugartrabajo;
    }

    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }

    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    public Date getFechaalta() {
        return this.fechaalta;
    }

    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    public Date getFechabaja() {
        return this.fechabaja;
    }

    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    public Double getSueldo() {
        return this.sueldo;
    }

    public void setSueldo(Double sueldo) {
        this.sueldo = sueldo;
    }

    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    public boolean isAdministrador() {
        return this.administrador;
    }

    public String getAdmin() {
        return this.administrador == true ? "Sí" : "No";
    }

    public void setAdministrador(boolean administrador) {
        this.administrador = administrador;
    }

    public boolean isActivo() {
        return this.activo;
    }

    public String getActiv() {
        return this.activo == true ? "Sí" : "No";
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

   /* public Set getCitas() {
        return this.citas;
    }

    public void setCitas(Set citas) {
        this.citas = citas;
    }

    public Set getRecetas() {
        return this.recetas;
    }

    public void setRecetas(Set recetas) {
        this.recetas = recetas;
    }

    public Set getPacientes() {
        return this.pacientes;
    }

    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }

    public Set getOdontogramas() {
        return this.odontogramas;
    }

    public void setOdontogramas(Set odontogramas) {
        this.odontogramas = odontogramas;
    }

    public Set getConsultas() {
        return this.consultas;
    }

    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }

    public Set getInformes() {
        return this.informes;
    }

    public void setInformes(Set informes) {
        this.informes = informes;
    }*/

    @Override
    public String toString() {
        return nombre + " " + apellidopaterno;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || !(o instanceof Medico)) {
            return false;
        }
        if (o == this) {
            return true;
        }

        //Medico medico = (Medico) o;
        return medicoid == ((Medico) o).getMedicoid();
    }
}
