package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Transient;
import org.hibernate.Hibernate;

/**
 * Odontograma generated by hbm2java
 */
public class Odontograma implements java.io.Serializable {

    private int odontogramaid;
    private Paciente paciente;
    private Medico medico;
    private Date fecha;
    private String numerodepieza;
    private String materialrelleno;
    private String materialsellado;
    private String descripciontratamiento;
    private String realizado;
    private String presupuesto;
    private String formadepago;
    private String image;
   // private Set archivos = new HashSet(0);
    //private Set tratamientos = new HashSet(0);
    @Transient
    private Tratamiento tratamiento;
    @Transient
    private String dateForFilter;
    @Transient
    private Integer position;

    public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Tratamiento getTratamiento() {
        return tratamiento;
    }

    public void setTratamiento(Tratamiento tratamiento) {
        this.tratamiento = tratamiento;
    }

    public Odontograma() {
        tratamiento = new Tratamiento();
    }

    public Odontograma(int odontogramaid, Paciente paciente, Medico medico, Date fecha, String numerodepieza, String materialrelleno, String materialsellado, String descripciontratamiento, String realizado, String presupuesto, String formadepago, String image) {
        this.odontogramaid = odontogramaid;
        this.paciente = paciente;
        this.medico = medico;
        this.fecha = fecha;
        this.numerodepieza = numerodepieza;
        this.materialrelleno = materialrelleno;
        this.materialsellado = materialsellado;
        this.descripciontratamiento = descripciontratamiento;
        this.realizado = realizado;
        this.presupuesto = presupuesto;
        this.formadepago = formadepago;
        this.image = image;
    }

    public Odontograma(int odontogramaid, Paciente paciente, Medico medico, Date fecha, String numerodepieza, String materialrelleno, String materialsellado, String descripciontratamiento, String realizado, String presupuesto, String formadepago, String image, Set archivos, Set tratamientos) {
        this.odontogramaid = odontogramaid;
        this.paciente = paciente;
        this.medico = medico;
        this.fecha = fecha;
        this.numerodepieza = numerodepieza;
        this.materialrelleno = materialrelleno;
        this.materialsellado = materialsellado;
        this.descripciontratamiento = descripciontratamiento;
        this.realizado = realizado;
        this.presupuesto = presupuesto;
        this.formadepago = formadepago;
      /*  this.archivos = archivos;
         this.tratamientos = tratamientos;*/

        this.image = image;
    }

    public int getOdontogramaid() {
        return this.odontogramaid;
    }

    public void setOdontogramaid(int odontogramaid) {
        this.odontogramaid = odontogramaid;
    }

    public Paciente getPaciente() {
        Hibernate.initialize(this.paciente);
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public Medico getMedico() {
        Hibernate.initialize(this.medico);
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNumerodepieza() {
        return this.numerodepieza;
    }

    public void setNumerodepieza(String numerodepieza) {
        this.numerodepieza = numerodepieza;
    }

    public String getMaterialrelleno() {
        return this.materialrelleno;
    }

    public void setMaterialrelleno(String materialrelleno) {
        this.materialrelleno = materialrelleno;
    }

    public String getMaterialsellado() {
        return this.materialsellado;
    }

    public void setMaterialsellado(String materialsellado) {
        this.materialsellado = materialsellado;
    }

    public String getDescripciontratamiento() {
        return this.descripciontratamiento;
    }

    public void setDescripciontratamiento(String descripciontratamiento) {
        this.descripciontratamiento = descripciontratamiento;
    }

    public String getRealizado() {
        return this.realizado;
    }

    public void setRealizado(String realizado) {
        this.realizado = realizado;
    }

    public String getPresupuesto() {
        return this.presupuesto;
    }

    public void setPresupuesto(String presupuesto) {
        this.presupuesto = presupuesto;
    }

    public String getFormadepago() {
        return this.formadepago;
    }

    public void setFormadepago(String formadepago) {
        this.formadepago = formadepago;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    /*public Set getArchivos() {
        return this.archivos;
    }

    public void setArchivos(Set archivos) {
        this.archivos = archivos;
    }

    public Set getTratamientos() {
        return this.tratamientos;
    }

    public void setTratamientos(Set tratamientos) {
        this.tratamientos = tratamientos;
    }*/

    @Override
    public String toString() {
        return odontogramaid + " " + paciente.getNombre();
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Odontograma)) {
            return false;
        }
        Odontograma odontograma = (Odontograma) o;
        return (this.odontogramaid == odontograma.odontogramaid);

    }
}
