package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Transient;
import org.hibernate.Hibernate;

/**
 * Receta generated by hbm2java
 */
public class Receta implements java.io.Serializable {

    private int recetaid;
    private Paciente paciente;
    private Medico medico;
    private Date fechaprescripcion;
    private String farmaco;
    private int numeroenvases;
    private int numero;
    private String duraciontratamiento;
    private String posologia;
    private String pauta;
    private String informacionadicional;

    public Receta() {
    }

    public Receta(int recetaid, Paciente paciente, Medico medico, Date fechaprescripcion, String farmaco, int numeroenvases, int numero,String duraciontratamiento, String posologia, String pauta, String informacionadicional) {
        this.recetaid = recetaid;
        this.paciente = paciente;
        this.medico = medico;
        this.fechaprescripcion = fechaprescripcion;
        this.farmaco = farmaco;
        this.numeroenvases = numeroenvases;
        this.numero = numero;
        this.duraciontratamiento = duraciontratamiento;
        this.posologia = posologia;
        this.pauta = pauta;
        this.informacionadicional = informacionadicional;
    }

     @Transient
    private String dateForFilter;
    @Transient
    private Integer position;

    public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }
    public int getRecetaid() {
        return this.recetaid;
    }

    public void setRecetaid(int recetaid) {
        this.recetaid = recetaid;
    }

    public Paciente getPaciente() {
        Hibernate.initialize(this.paciente);
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public Medico getMedico() {
        Hibernate.initialize(this.medico);
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

    public Date getFechaprescripcion() {
        return this.fechaprescripcion;
    }

    public void setFechaprescripcion(Date fechaprescripcion) {
        this.fechaprescripcion = fechaprescripcion;
    }

    public String getFarmaco() {
        return this.farmaco;
    }

    public void setFarmaco(String farmaco) {
        this.farmaco = farmaco;
    }

    public int getNumeroenvases() {
        return this.numeroenvases;
    }

    public void setNumeroenvases(int numeroenvases) {
        this.numeroenvases = numeroenvases;
    }
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getDuraciontratamiento() {
        return this.duraciontratamiento;
    }

    public void setDuraciontratamiento(String duraciontratamiento) {
        this.duraciontratamiento = duraciontratamiento;
    }

    public String getPosologia() {
        return this.posologia;
    }

    public void setPosologia(String posologia) {
        this.posologia = posologia;
    }

    public String getPauta() {
        return this.pauta;
    }

    public void setPauta(String pauta) {
        this.pauta = pauta;
    }

    public String getInformacionadicional() {
        return this.informacionadicional;
    }

    public void setInformacionadicional(String informacionadicional) {
        this.informacionadicional = informacionadicional;
    }

    @Override
    public String toString() {
        return recetaid + " " + paciente.getNombre();
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || !(o instanceof Receta)) {
            return false;
        }
        Receta receta = (Receta) o;
        return (this.recetaid == receta.recetaid);

    }
}
