package Entity;
// Generated 15-jul-2014 19:36:51 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Transient;
import org.hibernate.Hibernate;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento implements java.io.Serializable {

    private int tratamientoid;
    private Odontograma odontograma;
    private String tratamiento;
    private String tipo;
    private Set consultas = new HashSet(0);
    @Transient
    private Integer position;

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Tratamiento() {
    }

    public Tratamiento(int tratamientoid, String tratamiento, String tipo) {
        this.tratamientoid = tratamientoid;
        this.tratamiento = tratamiento;
        this.tipo = tipo;
    }

    public Tratamiento(int tratamientoid, Odontograma odontograma, String tratamiento, String tipo, Set consultas, Set odontogramas) {
        this.tratamientoid = tratamientoid;
        this.tratamiento = tratamiento;
        this.odontograma = odontograma;
        this.tipo = tipo;
        this.consultas = consultas;

    }

    public int getTratamientoid() {
        return this.tratamientoid;
    }

    public void setTratamientoid(int tratamientoid) {
        this.tratamientoid = tratamientoid;
    }

    public Odontograma getOdontograma() {
        Hibernate.initialize(this.odontograma);
        return this.odontograma;
    }

    public void setOdontograma(Odontograma odontograma) {
        this.odontograma = odontograma;
    }

    public String getTratamiento() {
        return this.tratamiento;
    }

    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Set getConsultas() {
        return this.consultas;
    }

    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }

  

    @Override
    public String toString() {
        return tratamiento;
    }

    @Override
    public boolean equals(Object o) {

        if (o == null || !(o instanceof Tratamiento)) {
            return false;
        }
        if (o == this) {
            return true;
        }

        return tratamientoid == ((Tratamiento) o).getTratamientoid();

    }
}
