package entidades;
// Generated 20-mar-2017 23:16:03 by Hibernate Tools 3.5.0.Final

/**
 * Param generated by hbm2java
 */
public class Param implements java.io.Serializable {

	private int parId;
	private String parNemonico;
	private String parDescripcion;
	private String parValor;

	public Param() {
	}

	public Param(int parId, String parNemonico, String parDescripcion, String parValor) {
		this.parId = parId;
		this.parNemonico = parNemonico;
		this.parDescripcion = parDescripcion;
		this.parValor = parValor;
	}

	public int getParId() {
		return this.parId;
	}

	public void setParId(int parId) {
		this.parId = parId;
	}

	public String getParNemonico() {
		return this.parNemonico;
	}

	public void setParNemonico(String parNemonico) {
		this.parNemonico = parNemonico;
	}

	public String getParDescripcion() {
		return this.parDescripcion;
	}

	public void setParDescripcion(String parDescripcion) {
		this.parDescripcion = parDescripcion;
	}

	public String getParValor() {
		return this.parValor;
	}

	public void setParValor(String parValor) {
		this.parValor = parValor;
	}

}
