package entidades;
// Generated 20-mar-2017 23:16:03 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * PerfilRecurso generated by hbm2java
 */
public class PerfilRecurso implements java.io.Serializable {

	private int recuId;
	private ParametroDetalle parametroDetalle;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModif;

	public PerfilRecurso() {
	}

	public PerfilRecurso(int recuId, ParametroDetalle parametroDetalle, int audUsuCrea, int audUsuModi,
			Date audFechaCrea, Date audFechaModif) {
		this.recuId = recuId;
		this.parametroDetalle = parametroDetalle;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModif = audFechaModif;
	}

	public int getRecuId() {
		return this.recuId;
	}

	public void setRecuId(int recuId) {
		this.recuId = recuId;
	}

	public ParametroDetalle getParametroDetalle() {
		return this.parametroDetalle;
	}

	public void setParametroDetalle(ParametroDetalle parametroDetalle) {
		this.parametroDetalle = parametroDetalle;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModif() {
		return this.audFechaModif;
	}

	public void setAudFechaModif(Date audFechaModif) {
		this.audFechaModif = audFechaModif;
	}

}
