package entidades;
// Generated 20-mar-2017 23:16:03 by Hibernate Tools 3.5.0.Final

/**
 * VistaReporteAbstract generated by hbm2java
 */
public class VistaReporteAbstract implements java.io.Serializable {

	private VistaReporteAbstractId id;

	public VistaReporteAbstract() {
	}

	public VistaReporteAbstract(VistaReporteAbstractId id) {
		this.id = id;
	}

	public VistaReporteAbstractId getId() {
		return this.id;
	}

	public void setId(VistaReporteAbstractId id) {
		this.id = id;
	}

}
