package entidades;
// Generated 20-mar-2017 23:16:03 by Hibernate Tools 3.5.0.Final

/**
 * VistaReporteEstudiantes generated by hbm2java
 */
public class VistaReporteEstudiantes implements java.io.Serializable {

	private VistaReporteEstudiantesId id;

	public VistaReporteEstudiantes() {
	}

	public VistaReporteEstudiantes(VistaReporteEstudiantesId id) {
		this.id = id;
	}

	public VistaReporteEstudiantesId getId() {
		return this.id;
	}

	public void setId(VistaReporteEstudiantesId id) {
		this.id = id;
	}

}
