package entidades;
// Generated 20-mar-2017 23:16:03 by Hibernate Tools 3.5.0.Final

/**
 * VistaReporteAbstractId generated by hbm2java
 */
public class VistaReporteAbstractId implements java.io.Serializable {

	private String anio;
	private String temDescripcion;
	private String docNombres;
	private String docApellidos;
	private String segDocumento;
	private String segPathDocumento;
	private String segObservaciones;

	public VistaReporteAbstractId() {
	}

	public VistaReporteAbstractId(String anio, String temDescripcion, String docNombres, String docApellidos,
			String segDocumento, String segPathDocumento, String segObservaciones) {
		this.anio = anio;
		this.temDescripcion = temDescripcion;
		this.docNombres = docNombres;
		this.docApellidos = docApellidos;
		this.segDocumento = segDocumento;
		this.segPathDocumento = segPathDocumento;
		this.segObservaciones = segObservaciones;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public String getTemDescripcion() {
		return this.temDescripcion;
	}

	public void setTemDescripcion(String temDescripcion) {
		this.temDescripcion = temDescripcion;
	}

	public String getDocNombres() {
		return this.docNombres;
	}

	public void setDocNombres(String docNombres) {
		this.docNombres = docNombres;
	}

	public String getDocApellidos() {
		return this.docApellidos;
	}

	public void setDocApellidos(String docApellidos) {
		this.docApellidos = docApellidos;
	}

	public String getSegDocumento() {
		return this.segDocumento;
	}

	public void setSegDocumento(String segDocumento) {
		this.segDocumento = segDocumento;
	}

	public String getSegPathDocumento() {
		return this.segPathDocumento;
	}

	public void setSegPathDocumento(String segPathDocumento) {
		this.segPathDocumento = segPathDocumento;
	}

	public String getSegObservaciones() {
		return this.segObservaciones;
	}

	public void setSegObservaciones(String segObservaciones) {
		this.segObservaciones = segObservaciones;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaReporteAbstractId))
			return false;
		VistaReporteAbstractId castOther = (VistaReporteAbstractId) other;

		return ((this.getAnio() == castOther.getAnio()) || (this.getAnio() != null && castOther.getAnio() != null
				&& this.getAnio().equals(castOther.getAnio())))
				&& ((this.getTemDescripcion() == castOther.getTemDescripcion())
						|| (this.getTemDescripcion() != null && castOther.getTemDescripcion() != null
								&& this.getTemDescripcion().equals(castOther.getTemDescripcion())))
				&& ((this.getDocNombres() == castOther.getDocNombres()) || (this.getDocNombres() != null
						&& castOther.getDocNombres() != null && this.getDocNombres().equals(castOther.getDocNombres())))
				&& ((this.getDocApellidos() == castOther.getDocApellidos())
						|| (this.getDocApellidos() != null && castOther.getDocApellidos() != null
								&& this.getDocApellidos().equals(castOther.getDocApellidos())))
				&& ((this.getSegDocumento() == castOther.getSegDocumento())
						|| (this.getSegDocumento() != null && castOther.getSegDocumento() != null
								&& this.getSegDocumento().equals(castOther.getSegDocumento())))
				&& ((this.getSegPathDocumento() == castOther.getSegPathDocumento())
						|| (this.getSegPathDocumento() != null && castOther.getSegPathDocumento() != null
								&& this.getSegPathDocumento().equals(castOther.getSegPathDocumento())))
				&& ((this.getSegObservaciones() == castOther.getSegObservaciones())
						|| (this.getSegObservaciones() != null && castOther.getSegObservaciones() != null
								&& this.getSegObservaciones().equals(castOther.getSegObservaciones())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAnio() == null ? 0 : this.getAnio().hashCode());
		result = 37 * result + (getTemDescripcion() == null ? 0 : this.getTemDescripcion().hashCode());
		result = 37 * result + (getDocNombres() == null ? 0 : this.getDocNombres().hashCode());
		result = 37 * result + (getDocApellidos() == null ? 0 : this.getDocApellidos().hashCode());
		result = 37 * result + (getSegDocumento() == null ? 0 : this.getSegDocumento().hashCode());
		result = 37 * result + (getSegPathDocumento() == null ? 0 : this.getSegPathDocumento().hashCode());
		result = 37 * result + (getSegObservaciones() == null ? 0 : this.getSegObservaciones().hashCode());
		return result;
	}

}
