package Entity;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante implements java.io.Serializable {

	private int estId;
	private ParametroDetalle parametroDetalle;
	private LugarGeografico lugarGeografico;
	private String estCedula;
	private String estNombres;
	private String estApellidos;
	private String estTelefono;
	private String estDireccion;
	private String estCelular;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;
	private Set temas = new HashSet(0);
	private ParametroDetalle parametroDetalleFacultad;
	private ParametroDetalle parametroDetalleProfesion;
	private String estPassword;


	public Estudiante() {
	}

	public Estudiante(int estId, ParametroDetalle parametroDetalle,
			LugarGeografico lugarGeografico, String estCedula,
			String estNombres, String estApellidos, String estTelefono,
			String estDireccion, String estCelular, int audUsuCrea,
			int audUsuModi, Date audFechaCrea, Date audFechaModi, ParametroDetalle parametroDetalleFactultad, 
			ParametroDetalle parametroDetalleProfesion, String estPassword) {
		this.estId = estId;
		this.parametroDetalle = parametroDetalle;
		this.lugarGeografico = lugarGeografico;
		this.estCedula = estCedula;
		this.estNombres = estNombres;
		this.estApellidos = estApellidos;
		this.estTelefono = estTelefono;
		this.estDireccion = estDireccion;
		this.estCelular = estCelular;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		this.parametroDetalleFacultad = parametroDetalleFactultad;
		this.parametroDetalleProfesion = parametroDetalleProfesion;
		this.estPassword = estPassword;
	}

	public Estudiante(int estId, ParametroDetalle parametroDetalle,
			LugarGeografico lugarGeografico, String estCedula,
			String estNombres, String estApellidos, String estTelefono,
			String estDireccion, String estCelular, int audUsuCrea,
			int audUsuModi, Date audFechaCrea, Date audFechaModi, Set temas, ParametroDetalle parametroDetalleFactultad, ParametroDetalle parametroDetalleProfesion,
			String estPassword) {
		this.estId = estId;
		this.parametroDetalle = parametroDetalle;
		this.lugarGeografico = lugarGeografico;
		this.estCedula = estCedula;
		this.estNombres = estNombres;
		this.estApellidos = estApellidos;
		this.estTelefono = estTelefono;
		this.estDireccion = estDireccion;
		this.estCelular = estCelular;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		this.temas = temas;
		this.parametroDetalleFacultad = parametroDetalleFactultad;
		this.parametroDetalleProfesion = parametroDetalleProfesion;
		this.estPassword = estPassword;
	}

    @Transient
    private Integer position;

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }	
	
	public int getEstId() {
		return this.estId;
	}

	public void setEstId(int estId) {
		this.estId = estId;
	}

	public ParametroDetalle getParametroDetalle() {
		return this.parametroDetalle;
	}

	public void setParametroDetalle(ParametroDetalle parametroDetalle) {
		this.parametroDetalle = parametroDetalle;
	}

	public LugarGeografico getLugarGeografico() {
		return this.lugarGeografico;
	}

	public void setLugarGeografico(LugarGeografico lugarGeografico) {
		this.lugarGeografico = lugarGeografico;
	}

	public String getEstCedula() {
		return this.estCedula;
	}

	public void setEstCedula(String estCedula) {
		this.estCedula = estCedula;
	}

	public String getEstNombres() {
		return this.estNombres;
	}

	public void setEstNombres(String estNombres) {
		this.estNombres = estNombres;
	}

	public String getEstApellidos() {
		return this.estApellidos;
	}

	public void setEstApellidos(String estApellidos) {
		this.estApellidos = estApellidos;
	}

	public String getEstTelefono() {
		return this.estTelefono;
	}

	public void setEstTelefono(String estTelefono) {
		this.estTelefono = estTelefono;
	}

	public String getEstDireccion() {
		return this.estDireccion;
	}

	public void setEstDireccion(String estDireccion) {
		this.estDireccion = estDireccion;
	}

	public String getEstCelular() {
		return this.estCelular;
	}

	public void setEstCelular(String estCelular) {
		this.estCelular = estCelular;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	public Set getTemas() {
		return this.temas;
	}

	public void setTemas(Set temas) {
		this.temas = temas;
	}

    @Override
    public String toString() {
        return this.estApellidos + " " + this.estNombres;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof Estudiante)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        return this.estId == ((Estudiante) obj).getEstId();
    }
    
	public ParametroDetalle getParametroDetalleFacultad() {
		return parametroDetalleFacultad;
	}

	public void setParametroDetalleFacultad(
			ParametroDetalle parametroDetalleFacultad) {
		this.parametroDetalleFacultad = parametroDetalleFacultad;
	}
	
	public ParametroDetalle getParametroDetalleProfesion() {
		return parametroDetalleProfesion;
	}

	public void setParametroDetalleProfesion(
			ParametroDetalle parametroDetalleProfesion) {
		this.parametroDetalleProfesion = parametroDetalleProfesion;
	}

	public String getEstPassword() {
		return estPassword;
	}

	public void setEstPassword(String estPassword) {
		this.estPassword = estPassword;
	}		
	
}
