package Entity;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parametro generated by hbm2java
 */
public class Parametro implements java.io.Serializable {

	private int parId;
	private String parDesCorta;
	private String parDesLarga;
	private String parSimbolo;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModif;
	//private Set parametroDetalles = new HashSet(0);

	public Parametro() {
		
	}

	public Parametro(int parId, String parDesCorta, String parDesLarga,
			String parSimbolo, int audUsuCrea, int audUsuModi,
			Date audFechaCrea, Date audFechaModif) {
		this.parId = parId;
		this.parDesCorta = parDesCorta;
		this.parDesLarga = parDesLarga;
		this.parSimbolo = parSimbolo;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModif = audFechaModif;
	}

	/*public Parametro(int parId, String parDesCorta, String parDesLarga,
			String parSimbolo, int audUsuCrea, int audUsuModi,
			Date audFechaCrea, Date audFechaModif, Set parametroDetalles) {
		this.parId = parId;
		this.parDesCorta = parDesCorta;
		this.parDesLarga = parDesLarga;
		this.parSimbolo = parSimbolo;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModif = audFechaModif;
		//this.parametroDetalles = parametroDetalles;
	}*/

	public int getParId() {
		return this.parId;
	}

	public void setParId(int parId) {
		this.parId = parId;
	}

	public String getParDesCorta() {
		return this.parDesCorta;
	}

	public void setParDesCorta(String parDesCorta) {
		this.parDesCorta = parDesCorta;
	}

	public String getParDesLarga() {
		return this.parDesLarga;
	}

	public void setParDesLarga(String parDesLarga) {
		this.parDesLarga = parDesLarga;
	}

	public String getParSimbolo() {
		return this.parSimbolo;
	}

	public void setParSimbolo(String parSimbolo) {
		this.parSimbolo = parSimbolo;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModif() {
		return this.audFechaModif;
	}

	public void setAudFechaModif(Date audFechaModif) {
		this.audFechaModif = audFechaModif;
	}
	
    @Override
    public String toString() {
        return  parDesCorta;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof Parametro)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        return this.parId == ((Parametro) obj).getParId();
    }

}
