package Entity;

import javax.persistence.Transient;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

/**
 * Param generated by hbm2java
 */
public class DataReporteEstadistica implements java.io.Serializable {

	private String descripcion;
	private int cantidad;	

	public DataReporteEstadistica() {
	}

	
	public DataReporteEstadistica(int cantidad, String descripcion) {
		this.cantidad = cantidad;
		this.descripcion = descripcion;
	}


	public String getDescripcion() {
		return descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	public int getCantidad() {
		return cantidad;
	}


	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	
	
}
