package Entity;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;

import org.hibernate.Hibernate;

/**
 * LugarGeografico generated by hbm2java
 */
public class LugarGeografico implements java.io.Serializable {

	private int idLugar;
	private LugarGeografico lugarGeograficop;
	private String desCorta;
	private String desLarga;
	private int nivel;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;
	private Set estudiantes = new HashSet(0);
	private Set lugarGeograficos = new HashSet(0);

	public LugarGeografico() {
	}

	public LugarGeografico(int idLugar, LugarGeografico lugarGeografico,
			String desCorta, String desLarga, int nivel, int audUsuCrea,
			int audUsuModi, Date audFechaCrea, Date audFechaModi) {
		this.idLugar = idLugar;
		this.lugarGeograficop = lugarGeografico;
		this.desCorta = desCorta;
		this.desLarga = desLarga;
		this.nivel = nivel;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

	public LugarGeografico(int idLugar, LugarGeografico lugarGeografico,
			String desCorta, String desLarga, int nivel, int audUsuCrea,
			int audUsuModi, Date audFechaCrea, Date audFechaModi,
			Set estudiantes, Set lugarGeograficos) {
		this.idLugar = idLugar;
		this.lugarGeograficop = lugarGeografico;
		this.desCorta = desCorta;
		this.desLarga = desLarga;
		this.nivel = nivel;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		this.estudiantes = estudiantes;
		this.lugarGeograficos = lugarGeograficos;
	}
	
	@Transient
    private Integer position;

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

	public int getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(int idLugar) {
		this.idLugar = idLugar;
	}

	public LugarGeografico getLugarGeograficop() {
		return this.lugarGeograficop;
	}

	public void setLugarGeograficop(LugarGeografico lugarGeograficop) {
		this.lugarGeograficop = lugarGeograficop;
	}

	public String getDesCorta() {
		return this.desCorta;
	}

	public void setDesCorta(String desCorta) {
		this.desCorta = desCorta;
	}

	public String getDesLarga() {
		return this.desLarga;
	}

	public void setDesLarga(String desLarga) {
		this.desLarga = desLarga;
	}

	public int getNivel() {
		return this.nivel;
	}

	public void setNivel(int nivel) {
		this.nivel = nivel;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	public Set getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Set estudiantes) {
		this.estudiantes = estudiantes;
	}

	public Set getLugarGeograficos() {
		return this.lugarGeograficos;
	}

	public void setLugarGeograficos(Set lugarGeograficos) {
		this.lugarGeograficos = lugarGeograficos;
	}
	
    @Override
    public String toString() {
        return this.desCorta;
    }
	
    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof LugarGeografico)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        return this.idLugar == ((LugarGeografico) obj).getIdLugar();
    }

}
