package Entity;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;

import org.hibernate.Hibernate;

/**
 * ParametroDetalle generated by hbm2java
 */
public class ParametroDetalle implements java.io.Serializable {

	private String padCodigo;
	private Parametro parametro;
	private String padDesCorta;
	private String padDesLarga;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;

	public ParametroDetalle() {
	}

	public ParametroDetalle(String padCodigo, Parametro parametro,
			String padDesCorta, String padDesLarga, int audUsuCrea,
			int audUsuModi, Date audFechaCrea, Date audFechaModi) {
		this.padCodigo = padCodigo;
		this.parametro = parametro;
		this.padDesCorta = padDesCorta;
		this.padDesLarga = padDesLarga;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

    //@Transient
    //private String dateForFilter;
    @Transient
    private Integer position;

    /*public String getDateForFilter() {
        return dateForFilter;
    }

    public void setDateForFilter(String dateForFilter) {
        this.dateForFilter = dateForFilter;
    }*/

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }
	
	public String getPadCodigo() {
		return this.padCodigo;
	}

	public void setPadCodigo(String padCodigo) {
		this.padCodigo = padCodigo;
	}

	public Parametro getParametro() {
		Hibernate.initialize(this.parametro);
		return this.parametro;
	}

	public void setParametro(Parametro parametro) {		
		this.parametro = parametro;
	}

	public String getPadDesCorta() {
		return this.padDesCorta;
	}

	public void setPadDesCorta(String padDesCorta) {
		this.padDesCorta = padDesCorta;
	}

	public String getPadDesLarga() {
		return this.padDesLarga;
	}

	public void setPadDesLarga(String padDesLarga) {
		this.padDesLarga = padDesLarga;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}	
	
    @Override
    public String toString() {
        return padDesCorta;
    }
	
	@Override
    public boolean equals(Object o) {
		/*if (obj == null || !(obj instanceof ParametroDetalle)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        return padCodigo == ((ParametroDetalle) obj).getPadCodigo();*/	
		//ojo eta
        if (!(o instanceof ParametroDetalle)) {
            return false;
        }
        ParametroDetalle pDetalle = (ParametroDetalle) o;
        //return (this.padCodigo == pDetalle.getPadCodigo());
        return (this.padCodigo.equals(pDetalle.getPadCodigo()));

    }

}
