package Entity;

// Generated 16/01/2015 11:00:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Transient;

import Entity.Docente;
import Entity.Tema;

/**
 * Seguimiento generated by hbm2java
 */
public class SeguimientoTesis implements java.io.Serializable {

	private int segId;
	private Tema tema;
	private Docente docente;
	private Date segFecha;
	private String segDocumento;
	private String segPathDocumento;
	private String segObservaciones;
	private Integer audUsuModi;
	private Integer audUsuCrea;
	private Date audFechaCrea;
	private Date audFechaModi;

	public SeguimientoTesis() {
	}


	public SeguimientoTesis(int segId, Tema tema, Docente docente, Date segFecha,
			String segDocumento, String segPathDocumento,
			String segObservaciones, Integer audUsuModi, Integer audUsuCrea,
			Date audFechaCrea, Date audFechaModi) {
		this.segId = segId;
		this.tema = tema;
		this.docente = docente;
		this.segFecha = segFecha;
		this.segDocumento = segDocumento;
		this.segPathDocumento = segPathDocumento;
		this.segObservaciones = segObservaciones;
		this.audUsuModi = audUsuModi;
		this.audUsuCrea = audUsuCrea;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}
	
	
    @Transient
    private Integer position;

   
    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }	

	public int getSegId() {
		return this.segId;
	}

	public void setSegId(int segId) {
		this.segId = segId;
	}

	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}

	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	public Date getSegFecha() {
		return this.segFecha;
	}

	public void setSegFecha(Date segFecha) {
		this.segFecha = segFecha;
	}

	public String getSegDocumento() {
		return this.segDocumento;
	}

	public void setSegDocumento(String segDocumento) {
		this.segDocumento = segDocumento;
	}

	public String getSegPathDocumento() {
		return this.segPathDocumento;
	}

	public void setSegPathDocumento(String segPathDocumento) {
		this.segPathDocumento = segPathDocumento;
	}

	public String getSegObservaciones() {
		return this.segObservaciones;
	}

	public void setSegObservaciones(String segObservaciones) {
		this.segObservaciones = segObservaciones;
	}

	public Integer getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(Integer audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Integer getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(Integer audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	@Override
    public String toString() {
        return this.segDocumento;
    }
	
	@Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof SeguimientoTesis)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        return this.segId == ((SeguimientoTesis) obj).getSegId();
    }
}
