package Entity;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int usuId;
	private Docente docente;
	private ParametroDetalle parametroDetalleByPadCodigo;
	private ParametroDetalle parametroDetalleByParPadCodigo;
	private String usuDescripcion;
	private String usuLogin;
	private String usuPassword;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;

	public Usuario() {
	}

	public Usuario(int usuId, Docente docente,
			ParametroDetalle parametroDetalleByPadCodigo,
			ParametroDetalle parametroDetalleByParPadCodigo,
			String usuDescripcion, String usuLogin, String usuPassword,
			int audUsuCrea, int audUsuModi, Date audFechaCrea, Date audFechaModi) {
		this.usuId = usuId;
		this.docente = docente;
		this.parametroDetalleByPadCodigo = parametroDetalleByPadCodigo;
		this.parametroDetalleByParPadCodigo = parametroDetalleByParPadCodigo;
		this.usuDescripcion = usuDescripcion;
		this.usuLogin = usuLogin;
		this.usuPassword = usuPassword;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

	public int getUsuId() {
		return this.usuId;
	}

	public void setUsuId(int usuId) {
		this.usuId = usuId;
	}

	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	public ParametroDetalle getParametroDetalleByPadCodigo() {
		return this.parametroDetalleByPadCodigo;
	}

	public void setParametroDetalleByPadCodigo(
			ParametroDetalle parametroDetalleByPadCodigo) {
		this.parametroDetalleByPadCodigo = parametroDetalleByPadCodigo;
	}

	public ParametroDetalle getParametroDetalleByParPadCodigo() {
		return this.parametroDetalleByParPadCodigo;
	}

	public void setParametroDetalleByParPadCodigo(
			ParametroDetalle parametroDetalleByParPadCodigo) {
		this.parametroDetalleByParPadCodigo = parametroDetalleByParPadCodigo;
	}

	public String getUsuDescripcion() {
		return this.usuDescripcion;
	}

	public void setUsuDescripcion(String usuDescripcion) {
		this.usuDescripcion = usuDescripcion;
	}

	public String getUsuLogin() {
		return this.usuLogin;
	}

	public void setUsuLogin(String usuLogin) {
		this.usuLogin = usuLogin;
	}

	public String getUsuPassword() {
		return this.usuPassword;
	}

	public void setUsuPassword(String usuPassword) {
		this.usuPassword = usuPassword;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

}
