package Entity;
// Generated 24/03/2017 14:13:38 by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CampeonatoEquipo generated by hbm2java
 */
public class CampeonatoEquipo implements java.io.Serializable {

	private int campId;
	private Campeonato campeonato;
	private Equipo equipo;
	private String caeqEstado;
	private String audUsuCrea;
	private String audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;
	private Set<Requisitos> requisitoses = new HashSet<Requisitos>(0);
	private Set<Fixture> fixturesForSpoCampId3 = new HashSet<Fixture>(0);
	private Set<Fixture> fixturesForSpoCampId2 = new HashSet<Fixture>(0);
	private Set<Fixture> fixturesForSpoCampId = new HashSet<Fixture>(0);

	public CampeonatoEquipo() {
	}

	public CampeonatoEquipo(Campeonato campeonato, Equipo equipo) {
		this.campeonato = campeonato;
		this.equipo = equipo;
	}

	public CampeonatoEquipo(Campeonato campeonato, Equipo equipo, String caeqEstado, String audUsuCrea,
			String audUsuModi, Date audFechaCrea, Date audFechaModi, Set<Requisitos> requisitoses,
			Set<Fixture> fixturesForSpoCampId3, Set<Fixture> fixturesForSpoCampId2, Set<Fixture> fixturesForSpoCampId) {
		this.campeonato = campeonato;
		this.equipo = equipo;
		this.caeqEstado = caeqEstado;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		this.requisitoses = requisitoses;
		this.fixturesForSpoCampId3 = fixturesForSpoCampId3;
		this.fixturesForSpoCampId2 = fixturesForSpoCampId2;
		this.fixturesForSpoCampId = fixturesForSpoCampId;
	}

	public int getCampId() {
		return this.campId;
	}

	public void setCampId(int campId) {
		this.campId = campId;
	}

	public Campeonato getCampeonato() {
		return this.campeonato;
	}

	public void setCampeonato(Campeonato campeonato) {
		this.campeonato = campeonato;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getCaeqEstado() {
		return this.caeqEstado;
	}

	public void setCaeqEstado(String caeqEstado) {
		this.caeqEstado = caeqEstado;
	}

	public String getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(String audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public String getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(String audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	public Set<Requisitos> getRequisitoses() {
		return this.requisitoses;
	}

	public void setRequisitoses(Set<Requisitos> requisitoses) {
		this.requisitoses = requisitoses;
	}

	public Set<Fixture> getFixturesForSpoCampId3() {
		return this.fixturesForSpoCampId3;
	}

	public void setFixturesForSpoCampId3(Set<Fixture> fixturesForSpoCampId3) {
		this.fixturesForSpoCampId3 = fixturesForSpoCampId3;
	}

	public Set<Fixture> getFixturesForSpoCampId2() {
		return this.fixturesForSpoCampId2;
	}

	public void setFixturesForSpoCampId2(Set<Fixture> fixturesForSpoCampId2) {
		this.fixturesForSpoCampId2 = fixturesForSpoCampId2;
	}

	public Set<Fixture> getFixturesForSpoCampId() {
		return this.fixturesForSpoCampId;
	}

	public void setFixturesForSpoCampId(Set<Fixture> fixturesForSpoCampId) {
		this.fixturesForSpoCampId = fixturesForSpoCampId;
	}

}
