package Entity;
// Generated 24/03/2017 14:13:38 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * Caracteristica generated by hbm2java
 */
public class Caracteristica implements java.io.Serializable {

	private Integer caraId;
	private Campeonato campeonato;
	private ParametroDetalle parametroDetalleByPadeId;
	private ParametroDetalle parametroDetalleBySpoPadeId;
	private String caraTexto;
	private String audUsuCrea;
	private String audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;

	public Caracteristica() {
	}

	public Caracteristica(Campeonato campeonato, ParametroDetalle parametroDetalleByPadeId,
			ParametroDetalle parametroDetalleBySpoPadeId, String caraTexto, String audUsuCrea, String audUsuModi,
			Date audFechaCrea, Date audFechaModi) {
		this.campeonato = campeonato;
		this.parametroDetalleByPadeId = parametroDetalleByPadeId;
		this.parametroDetalleBySpoPadeId = parametroDetalleBySpoPadeId;
		this.caraTexto = caraTexto;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

	public Integer getCaraId() {
		return this.caraId;
	}

	public void setCaraId(Integer caraId) {
		this.caraId = caraId;
	}

	public Campeonato getCampeonato() {
		return this.campeonato;
	}

	public void setCampeonato(Campeonato campeonato) {
		this.campeonato = campeonato;
	}

	public ParametroDetalle getParametroDetalleByPadeId() {
		return this.parametroDetalleByPadeId;
	}

	public void setParametroDetalleByPadeId(ParametroDetalle parametroDetalleByPadeId) {
		this.parametroDetalleByPadeId = parametroDetalleByPadeId;
	}

	public ParametroDetalle getParametroDetalleBySpoPadeId() {
		return this.parametroDetalleBySpoPadeId;
	}

	public void setParametroDetalleBySpoPadeId(ParametroDetalle parametroDetalleBySpoPadeId) {
		this.parametroDetalleBySpoPadeId = parametroDetalleBySpoPadeId;
	}

	public String getCaraTexto() {
		return this.caraTexto;
	}

	public void setCaraTexto(String caraTexto) {
		this.caraTexto = caraTexto;
	}

	public String getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(String audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public String getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(String audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

}
