package Entity;
// Generated 24/03/2017 14:13:38 by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private Integer equiId;
	private Usuario usuario;
	private String equiNombre;
	private String equiDescripcion;
	private Date equiFechaFundacion;
	private String equiPresidente;
	private String equiMailContacto;
	private String equiDireccion;
	private String equiTelefono;
	private String equiObservaciones;
	private byte[] equiEscudo;
	private byte[] equiBandera;
	private String audUsuCrea;
	private String audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);
	private Set<CampeonatoEquipo> campeonatoEquipos = new HashSet<CampeonatoEquipo>(0);

	public Equipo() {
	}

	public Equipo(Usuario usuario, String equiNombre, String equiDescripcion, Date equiFechaFundacion,
			String equiPresidente, String equiMailContacto, String equiDireccion, String equiTelefono,
			String equiObservaciones, byte[] equiEscudo, byte[] equiBandera, String audUsuCrea, String audUsuModi,
			Date audFechaCrea, Date audFechaModi, Set<Jugador> jugadors, Set<CampeonatoEquipo> campeonatoEquipos) {
		this.usuario = usuario;
		this.equiNombre = equiNombre;
		this.equiDescripcion = equiDescripcion;
		this.equiFechaFundacion = equiFechaFundacion;
		this.equiPresidente = equiPresidente;
		this.equiMailContacto = equiMailContacto;
		this.equiDireccion = equiDireccion;
		this.equiTelefono = equiTelefono;
		this.equiObservaciones = equiObservaciones;
		this.equiEscudo = equiEscudo;
		this.equiBandera = equiBandera;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		this.jugadors = jugadors;
		this.campeonatoEquipos = campeonatoEquipos;
	}

	public Integer getEquiId() {
		return this.equiId;
	}

	public void setEquiId(Integer equiId) {
		this.equiId = equiId;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getEquiNombre() {
		return this.equiNombre;
	}

	public void setEquiNombre(String equiNombre) {
		this.equiNombre = equiNombre;
	}

	public String getEquiDescripcion() {
		return this.equiDescripcion;
	}

	public void setEquiDescripcion(String equiDescripcion) {
		this.equiDescripcion = equiDescripcion;
	}

	public Date getEquiFechaFundacion() {
		return this.equiFechaFundacion;
	}

	public void setEquiFechaFundacion(Date equiFechaFundacion) {
		this.equiFechaFundacion = equiFechaFundacion;
	}

	public String getEquiPresidente() {
		return this.equiPresidente;
	}

	public void setEquiPresidente(String equiPresidente) {
		this.equiPresidente = equiPresidente;
	}

	public String getEquiMailContacto() {
		return this.equiMailContacto;
	}

	public void setEquiMailContacto(String equiMailContacto) {
		this.equiMailContacto = equiMailContacto;
	}

	public String getEquiDireccion() {
		return this.equiDireccion;
	}

	public void setEquiDireccion(String equiDireccion) {
		this.equiDireccion = equiDireccion;
	}

	public String getEquiTelefono() {
		return this.equiTelefono;
	}

	public void setEquiTelefono(String equiTelefono) {
		this.equiTelefono = equiTelefono;
	}

	public String getEquiObservaciones() {
		return this.equiObservaciones;
	}

	public void setEquiObservaciones(String equiObservaciones) {
		this.equiObservaciones = equiObservaciones;
	}

	public byte[] getEquiEscudo() {
		return this.equiEscudo;
	}

	public void setEquiEscudo(byte[] equiEscudo) {
		this.equiEscudo = equiEscudo;
	}

	public byte[] getEquiBandera() {
		return this.equiBandera;
	}

	public void setEquiBandera(byte[] equiBandera) {
		this.equiBandera = equiBandera;
	}

	public String getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(String audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public String getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(String audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

	public Set<CampeonatoEquipo> getCampeonatoEquipos() {
		return this.campeonatoEquipos;
	}

	public void setCampeonatoEquipos(Set<CampeonatoEquipo> campeonatoEquipos) {
		this.campeonatoEquipos = campeonatoEquipos;
	}

}
