package Entity;
// Generated 24/03/2017 14:13:38 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * PerfilRecurso generated by hbm2java
 */
public class PerfilRecurso implements java.io.Serializable {

	private PerfilRecursoId id;
	private ParametroDetalle parametroDetalleBySpoPadeId;
	private ParametroDetalle parametroDetalleByPadeId;
	private String audUsuCrea;
	private String audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;

	public PerfilRecurso() {
	}

	public PerfilRecurso(PerfilRecursoId id, ParametroDetalle parametroDetalleBySpoPadeId,
			ParametroDetalle parametroDetalleByPadeId) {
		this.id = id;
		this.parametroDetalleBySpoPadeId = parametroDetalleBySpoPadeId;
		this.parametroDetalleByPadeId = parametroDetalleByPadeId;
	}

	public PerfilRecurso(PerfilRecursoId id, ParametroDetalle parametroDetalleBySpoPadeId,
			ParametroDetalle parametroDetalleByPadeId, String audUsuCrea, String audUsuModi, Date audFechaCrea,
			Date audFechaModi) {
		this.id = id;
		this.parametroDetalleBySpoPadeId = parametroDetalleBySpoPadeId;
		this.parametroDetalleByPadeId = parametroDetalleByPadeId;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

	public PerfilRecursoId getId() {
		return this.id;
	}

	public void setId(PerfilRecursoId id) {
		this.id = id;
	}

	public ParametroDetalle getParametroDetalleBySpoPadeId() {
		return this.parametroDetalleBySpoPadeId;
	}

	public void setParametroDetalleBySpoPadeId(ParametroDetalle parametroDetalleBySpoPadeId) {
		this.parametroDetalleBySpoPadeId = parametroDetalleBySpoPadeId;
	}

	public ParametroDetalle getParametroDetalleByPadeId() {
		return this.parametroDetalleByPadeId;
	}

	public void setParametroDetalleByPadeId(ParametroDetalle parametroDetalleByPadeId) {
		this.parametroDetalleByPadeId = parametroDetalleByPadeId;
	}

	public String getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(String audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public String getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(String audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

}
