package Entity;
// Generated 24/03/2017 14:13:38 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * Requisitos generated by hbm2java
 */
public class Requisitos implements java.io.Serializable {

	private Integer requId;
	private CampeonatoEquipo campeonatoEquipo;
	private String audUsuCrea;
	private String audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;

	public Requisitos() {
	}

	public Requisitos(CampeonatoEquipo campeonatoEquipo, String audUsuCrea, String audUsuModi, Date audFechaCrea,
			Date audFechaModi) {
		this.campeonatoEquipo = campeonatoEquipo;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

	public Integer getRequId() {
		return this.requId;
	}

	public void setRequId(Integer requId) {
		this.requId = requId;
	}

	public CampeonatoEquipo getCampeonatoEquipo() {
		return this.campeonatoEquipo;
	}

	public void setCampeonatoEquipo(CampeonatoEquipo campeonatoEquipo) {
		this.campeonatoEquipo = campeonatoEquipo;
	}

	public String getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(String audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public String getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(String audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

}
