package Entity;
// Generated 24/03/2017 14:13:38 by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer usuaId;
	private ParametroDetalle parametroDetalle;
	private String usuaLogin;
	private String usuaContrasena;
	private String audUsuCrea;
	private String audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;
	private Set<Equipo> equipos = new HashSet<Equipo>(0);

	public Usuario() {
	}

	public Usuario(ParametroDetalle parametroDetalle, String usuaLogin, String usuaContrasena, String audUsuCrea,
			String audUsuModi, Date audFechaCrea, Date audFechaModi, Set<Equipo> equipos) {
		this.parametroDetalle = parametroDetalle;
		this.usuaLogin = usuaLogin;
		this.usuaContrasena = usuaContrasena;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		this.equipos = equipos;
	}

	public Integer getUsuaId() {
		return this.usuaId;
	}

	public void setUsuaId(Integer usuaId) {
		this.usuaId = usuaId;
	}

	public ParametroDetalle getParametroDetalle() {
		return this.parametroDetalle;
	}

	public void setParametroDetalle(ParametroDetalle parametroDetalle) {
		this.parametroDetalle = parametroDetalle;
	}

	public String getUsuaLogin() {
		return this.usuaLogin;
	}

	public void setUsuaLogin(String usuaLogin) {
		this.usuaLogin = usuaLogin;
	}

	public String getUsuaContrasena() {
		return this.usuaContrasena;
	}

	public void setUsuaContrasena(String usuaContrasena) {
		this.usuaContrasena = usuaContrasena;
	}

	public String getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(String audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public String getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(String audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

	@Transient
    private Integer position;

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
