package Entity;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

	private int docId;
	private ParametroDetalle parametroDetalleByPadCodigo;
	private ParametroDetalle parametroDetalleByParPadCodigo;
	private String docNombres;
	private String docApellidos;
	private String docCedula;
	private String docCelular;
	private String docTelefono;
	private String docDireccion;
	private String docEstado;
	private int audUsuCrea;
	private int audUsuModi;
	private Date audFechaCrea;
	private Date audFechaModi;
	private String docLogin;
	private String docPassword;

	public Docente() {
	}

	public Docente(int docId, ParametroDetalle parametroDetalleByPadCodigo,
			ParametroDetalle parametroDetalleByParPadCodigo, String docNombres,
			String docApellidos, String docCedula, String docCelular,
			String docTelefono, String docDireccion, String docEstado,
			int audUsuCrea, int audUsuModi, Date audFechaCrea, Date audFechaModi) {
		this.docId = docId;
		this.parametroDetalleByPadCodigo = parametroDetalleByPadCodigo;
		this.parametroDetalleByParPadCodigo = parametroDetalleByParPadCodigo;
		this.docNombres = docNombres;
		this.docApellidos = docApellidos;
		this.docCedula = docCedula;
		this.docCelular = docCelular;
		this.docTelefono = docTelefono;
		this.docDireccion = docDireccion;
		this.docEstado = docEstado;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
	}

	/*public Docente(int docId, ParametroDetalle parametroDetalleByPadCodigo,
			ParametroDetalle parametroDetalleByParPadCodigo, String docNombres,
			String docApellidos, String docCedula, String docCelular,
			String docTelefono, String docDireccion, String docEstado,
			int audUsuCrea, int audUsuModi, Date audFechaCrea,
			Date audFechaModi) {
		this.docId = docId;
		this.parametroDetalleByPadCodigo = parametroDetalleByPadCodigo;
		this.parametroDetalleByParPadCodigo = parametroDetalleByParPadCodigo;
		this.docNombres = docNombres;
		this.docApellidos = docApellidos;
		this.docCedula = docCedula;
		this.docCelular = docCelular;
		this.docTelefono = docTelefono;
		this.docDireccion = docDireccion;
		this.docEstado = docEstado;
		this.audUsuCrea = audUsuCrea;
		this.audUsuModi = audUsuModi;
		this.audFechaCrea = audFechaCrea;
		this.audFechaModi = audFechaModi;
		//this.usuarios = usuarios;
	}*/
	@Transient
    private Integer position;

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }	
	
	public int getDocId() {
		return this.docId;
	}

	public void setDocId(int docId) {
		this.docId = docId;
	}

	public ParametroDetalle getParametroDetalleByPadCodigo() {
		return this.parametroDetalleByPadCodigo;
	}

	public void setParametroDetalleByPadCodigo(
			ParametroDetalle parametroDetalleByPadCodigo) {
		this.parametroDetalleByPadCodigo = parametroDetalleByPadCodigo;
	}

	public ParametroDetalle getParametroDetalleByParPadCodigo() {
		return this.parametroDetalleByParPadCodigo;
	}

	public void setParametroDetalleByParPadCodigo(
			ParametroDetalle parametroDetalleByParPadCodigo) {
		this.parametroDetalleByParPadCodigo = parametroDetalleByParPadCodigo;
	}

	public String getDocNombres() {
		return this.docNombres;
	}

	public void setDocNombres(String docNombres) {
		this.docNombres = docNombres;
	}

	public String getDocApellidos() {
		return this.docApellidos;
	}

	public void setDocApellidos(String docApellidos) {
		this.docApellidos = docApellidos;
	}

	public String getDocCedula() {
		return this.docCedula;
	}

	public void setDocCedula(String docCedula) {
		this.docCedula = docCedula;
	}

	public String getDocCelular() {
		return this.docCelular;
	}

	public void setDocCelular(String docCelular) {
		this.docCelular = docCelular;
	}

	public String getDocTelefono() {
		return this.docTelefono;
	}

	public void setDocTelefono(String docTelefono) {
		this.docTelefono = docTelefono;
	}

	public String getDocDireccion() {
		return this.docDireccion;
	}

	public void setDocDireccion(String docDireccion) {
		this.docDireccion = docDireccion;
	}

	public String getDocEstado() {
		return this.docEstado;
	}

	public void setDocEstado(String docEstado) {
		this.docEstado = docEstado;
	}

	public int getAudUsuCrea() {
		return this.audUsuCrea;
	}

	public void setAudUsuCrea(int audUsuCrea) {
		this.audUsuCrea = audUsuCrea;
	}

	public int getAudUsuModi() {
		return this.audUsuModi;
	}

	public void setAudUsuModi(int audUsuModi) {
		this.audUsuModi = audUsuModi;
	}

	public Date getAudFechaCrea() {
		return this.audFechaCrea;
	}

	public void setAudFechaCrea(Date audFechaCrea) {
		this.audFechaCrea = audFechaCrea;
	}

	public Date getAudFechaModi() {
		return this.audFechaModi;
	}

	public void setAudFechaModi(Date audFechaModi) {
		this.audFechaModi = audFechaModi;
	}

	public String getDocLogin() {
		return docLogin;
	}

	public void setDocLogin(String docLogin) {
		this.docLogin = docLogin;
	}

	public String getDocPassword() {
		return docPassword;
	}

	public void setDocPassword(String docPassword) {
		this.docPassword = docPassword;
	}
	
    @Override
    public String toString() {
        return this.docApellidos + " " + this.docNombres;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof Docente)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        return this.docId == ((Docente) obj).getDocId();
    }	
}
