package Entity;

import javax.persistence.Transient;
// default package
// Generated 28/12/2014 11:11:15 AM by Hibernate Tools 3.4.0.CR1

/**
 * Param generated by hbm2java
 */
public class Param implements java.io.Serializable {

	private int parId;
	private String parNemonico;
	private String parDescripcion;
	private String parValor;

	public Param() {
	}

    @Transient
    private Integer position;

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }	
	
	public Param(int parId, String parNemonico, String parDescripcion,
			String parValor) {
		this.parId = parId;
		this.parNemonico = parNemonico;
		this.parDescripcion = parDescripcion;
		this.parValor = parValor;
	}

	public int getParId() {
		return this.parId;
	}

	public void setParId(int parId) {
		this.parId = parId;
	}

	public String getParNemonico() {
		return this.parNemonico;
	}

	public void setParNemonico(String parNemonico) {
		this.parNemonico = parNemonico;
	}

	public String getParDescripcion() {
		return this.parDescripcion;
	}

	public void setParDescripcion(String parDescripcion) {
		this.parDescripcion = parDescripcion;
	}

	public String getParValor() {
		return this.parValor;
	}

	public void setParValor(String parValor) {
		this.parValor = parValor;
	}

}
